### ISSUE TITLE
V5 Bug - typescript declaration and package.json -> main is not same as build file bulidUrl.js 

### ISSUE THREAD

**Issue by meabed** [steverydz/build-url#39]
Thanks for new version release, I have upgraded and encounter 2 issues:

1- package.json -> main is not same as build file bulidUrl.js 
2- typescript declaration file is not included.

Let me If you need support fixing them - I could open a PR.

Thank again ❤️

**Comment by steverydz** [comment]
Thanks @meabed. I've just published a new release which fixes the package.json main field.

As this project isn't built with TypeScript why would it need a declaration file?

**Comment by meabed** [comment]
Thanks a lot Steve :) 

The the declaration file is used by typescript type checker for any library included in any typescript project - so the type must be either from the same module or definitelytyped or manually typed  and to declare it in the project it self, something like:
```
declare module 'build-url' {
  function BuildUrl(url: any, opt: any): string {}
  export = BuildUrl;
}
```

**Comment by steverydz** [comment]
I have considered rebuilding this with TypeScript before but so far haven't had the time. I'd still like to refactor the path and querystring functions as they've become overly complicated over time, so there is plenty to do!

I still don't understand why a non-TypeScript project would need a tool-specific file, which is what a declaration file appears to be. I've always intended this to be a JS library as is. The way it is used is up to the developer consuming it.

By all means you can fork this repo and submit a PR with a TypeScript version. I can't guarantee it will make it into the project, but it will be reviewed and tested for sure.

**Comment by Thilas** [comment]
I'm using this package from a typescript project of my own and when I updated it with the latest version from yesterday, because the declaration file has been removed (see https://github.com/steverydz/build-url/commit/2983ab587ab1d3da4f27b4b9b357f6bd4255b20f), my project is no longer able to build.

I surely understand your point above but I chose this package at first because it fit my need AND it had a declaration file.

Was it that of an issue to keep it? Thanks for your support.

**Comment by steverydz** [comment]
> I'm using this package from a typescript project of my own and when I updated it with the latest version from yesterday, because the declaration file has been removed (see 2983ab5), my project is no longer able to build.

There's been no functionality changes since 3.0.0 so you shouldn't have any problems if you rollback to that version for now.

> Was it that of an issue to keep it?

It was something to maintain which has no direct impact on this project. I really want to keep this thing as simple as possible. The declarations file was only there to begin with because I foolishly allowed it into the project without fully understanding its purpose.

From what I can see the standard is to add the definitions to https://github.com/DefinitelyTyped/DefinitelyTyped. If anyone wants to do that then please go ahead. If you need anything from me to make that possible then I'll be glad to help.

**Comment by Thilas** [comment]
@steverydz, thanks for your answer. One way to go is indeed to submit the former declaration file on this central repo. I may give it a try some time.

**Comment by meabed** [comment]
I have moved it to typescript in this PR #40 - It would be great it it got merged :)
